### ISSUE TITLE
MIDI out?

### ISSUE THREAD

**Issue by noises-modular** [sonic-insurgence/Gritty-Grids#1]
Thanks for publishing these changes to the Grids stock firmware. It seems like it could be altered to use the MIDI input pin as an output to control a drum machine (for example). Do you think it is feasible? I think it would entail adding another setting to the configuration mode to set MIDI to an output mode and adding a function to translate the triggers to MIDI notes.

**Comment by sonic-insurgence** [comment]
MIDI uses the hardware serial interface unit of the microcontroller. This unit has dedicated pins (pin 30 for serial input aka RxD, pin 31 for serial output aka TxD). As such the serial input cannot be repurposed as a serial output. On the board pin 30 is exposed as MIDI input, whereas pin 31 is not exposed and is already in use as the clock input of grids. So in my view it doesn't make sense to try to equip Grids with a MIDI output.

For a Grids-like drum machine that outputs MIDI data you might be interested in [MidiGAL](https://midisizer.com/midigal/) for which a MidiGrids firmware is available.

**Comment by noises-modular** [comment]
Wait a minute, why does the serial port for Tx need to use a hardware interface? Would there be a performance limitation? Arduino has a SoftwareSerial library which can be tweaked to send only and supports speeds up to 115200 bps. I am guessing Rx without the hardware port is more difficult because of buffering and timing, but Tx on an arbitrary pin seems more feasible since it just transmits data in an open loop.

https://docs.arduino.cc/learn/built-in-libraries/software-serial
https://forum.arduino.cc/t/using-only-tx-of-softwareserial-leaving-rx-pin-free/109623/3

**Comment by sonic-insurgence** [comment]
Yes, using a software serial interface is an option you can try. You have to check that there will be no timing issues, i. e. that the serial timing does not interfere with the timing of Grids drum pattern generator and vice versa. It could work but it would require to look into the code more deeply. For me this is too much of an effort.
